# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.create(name: "家醫科")
Category.create(name: "內科")
Category.create(name: "外科")
Category.create(name: "兒科")
Category.create(name: "婦產科")
Category.create(name: "中醫科")
Category.create(name: "泌尿科")
Category.create(name: "耳鼻喉科")
Category.create(name: "眼科")
Category.create(name: "皮膚科")
Category.create(name: "骨科")
Category.create(name: "神經科")
Category.create(name: "精神科")
Category.create(name: "復健科")
Category.create(name: "牙科")
Category.create(name: "整形外科")
Category.create(name: "腫瘤科")
Category.create(name: "急診醫學科")
Category.create(name: "職業醫學科")
Category.create(name: "麻醉科")
Category.create(name: "老人醫學科")
Category.create(name: "美容門診")
Category.create(name: "心理諮商")
Category.create(name: "病理科")

Area.create(name: "臺北市")
Area.create(name: "新北市")
Area.create(name: "桃園市")
Area.create(name: "臺中市")
Area.create(name: "臺南市")
Area.create(name: "高雄市")
Area.create(name: "基隆市")
Area.create(name: "嘉義市")
Area.create(name: "新竹市")
Area.create(name: "新竹縣")
Area.create(name: "苗栗縣")
Area.create(name: "彰化縣")
Area.create(name: "南投縣")
Area.create(name: "雲林縣")
Area.create(name: "嘉義縣")
Area.create(name: "屏東縣")
Area.create(name: "宜蘭縣")
Area.create(name: "花蓮縣")
Area.create(name: "臺東縣")
Area.create(name: "澎湖縣")
Area.create(name: "金門縣")
Area.create(name: "連江縣")
